# Generated by Django 3.2.9 on 2021-12-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_blog', '0008_auto_20211213_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='capa',
            field=models.ImageField(null=True, upload_to='artigos/'),
        ),
    ]
